# Site settings
title: Dev Day Conf 
email: "devdayconf@gmail.com"
description: Event for all communities.
baseurl: "/pt"
# url: "/pt"
# twitter_username: _devdayconf
# github_username: devdayconf

# Build settings
markdown: kramdown

highlighter: green


collections:
  home:
    output: true
    permalink: /home/:path/
  creator:
    output: true
    permalink: /creator/:path/
  rules:
    output: true
    permalink: /rules/:path/
  events:
    output: true
    permalink: /events/:path/
  contact:
    output: true
    permalink: /contact/:path/